package main;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import codewars_0221.sol.Kata;
import codewars_0222.sol.Solution;
import codewars_0223.sol.Vowels;
import codewars_0224.sol.Kata2;
import codewars_0225.sol.Troll;
import codewars_0226.sol.Kata3;
import codewars_0227.sol.Kata4;
import codewars_0228.sol.Solution2;
import codewars_0229.sol.SquareDigit;
import codewars_0301.sol.YesOrNO;
import codewars_0302.sol.Solution3;
import codewars_0303.sol.HighAndLow;
import codewars_0304.sol.RemoveChars;
import codewars_0305.sol.ArrayDiff;
import codewars_0306.sol.DescendingOrder;
import codewars_0307.sol.SquareSum;
import codewars_0308.sol.ListFiltering;
import codewars_0311.sol.HelloWorld;
import codewars_0312.sol.SpinWords;
import codewars_0313.sol.IsoGram;
import codewars_0314.sol.ToJadenCase;
import codewars_0315.sol.getXO;
import codewars_0316.sol.BitCounting;
import codewars_0317.sol.DuplicateEncoder;
import codewars_0318.sol.Accumul;
import codewars_0319.sol.FindOutlier;
import codewars_0320.sol.TenMinWalk;
import codewars_0321.sol.StringToNumber;
import codewars_0322.sol.PigLatin;
import codewars_0323.sol.DnaStrand;
import codewars_0324.sol.HumanReadableTime;
import codewars_0325.sol.RemoveStringSpaces;
import codewars_0326.sol.ConvertStringToCamelCase;
import codewars_0327.sol.HighestScoringWord;
import codewars_0328.sol.DoubleInteger;
import codewars_0329.sol.MaximumSubarray;
import codewars_0330.sol.Maskify;
import codewars_0331.sol.TwoToOne;
import codewars_0401.sol.Sum;
import codewars_0402.sol.GrowthOfAPopulation;
import codewars_0403.sol.PangramChecker;
import codewars_0404.sol.BinaryAddition;
import codewars_0405.sol.RgbToHex;
import codewars_0406.sol.FindTheNextPerfectSquare;
import codewars_0407.sol.FindTheOddInt;
import codewars_0408.sol.StringSplit;
import codewars_0409.sol.CountingSheep;
import codewars_0410.sol.YoureASquare;
import codewars_0411.sol.NumberUnits;
import codewars_0412.sol.DirReduction;
import codewars_0413.sol.WhoLikesIt;
import codewars_0414.sol.SumOfDigits;
import codewars_0415.sol.SmallestIntegerFinder;
import codewars_0416.sol.PersistentBugger;
import codewars_0417.sol.YourOrderPlease;
import codewars_0418.sol.SumOfPositive;
import codewars_0419.sol.FindTheUniqueNumber;
import codewars_0420.sol.ShortestWord;
import codewars_0421.sol.StringEndsWith;
import codewars_0422.sol.KeepHydrated;
import codewars_0423.sol.PeteTheBaker;
import codewars_0424.sol.FirstNonRepeatingCharacter;
import codewars_0425.sol.OnesAndZeros;
import codewars_0426.sol.Scramblies;
import codewars_0427.sol.ReverseWords;
import codewars_0428.sol.NumberOfPeopleInTheBus;
import codewars_0429.sol.BreakCamelCase;
import codewars_0430.sol.ReturningStrings;
import codewars_0501.sol.OddOrEven;
import codewars_0502.sol.IsNumberAPrime;
import codewars_0503.sol.TheHighestProfitWins;
import codewars_0504.sol.Testing123;
import codewars_0505.sol.WhichAreIn;
import codewars_0506.sol.Factorial;
import codewars_0507.sol.MakeUpperCase;
import codewars_0508.sol.OppositesAttract;
import codewars_0509.sol.DontGiveMeFive;
import codewars_0510.sol.BreakingChocolateProblem;
import codewars_0511.sol.BackspacesInString;
import codewars_0512.sol.GreetMe;
import codewars_0513.sol.SumOfNumbersFrom0ToN;
import codewars_0514.sol.LeapYears;
import codewars_0515.sol.FixStringCase;
import codewars_0516.sol.CalculateAverage;
import codewars_0517.sol.WriteNumberInExpandedForm;
import codewars_0518.sol.RockPaperScissors;
import codewars_0519.sol.BumpsIntheRoad;
import codewars_0520.sol.BasicMathematicalOperations;
import codewars_0521.sol.SumOfAngles;
import codewars_0522.sol.ReduceButGrow;
import codewars_0523.sol.NotVerySecure;
import codewars_0524.sol.AlternateCapitalization;
import codewars_0525.sol.RomanNumeralsEncoder;
import codewars_0526.sol.SchoolPaperwork;
import codewars_0527.sol.SumArrays;
import codewars_0528.sol.ReverseLetter;
import codewars_0529.sol.HowGoodAreYouReally;
import codewars_0530.sol.TwoSum;
import codewars_0531.sol.HumanReadableDurationFormat;
import codewars_0601.sol.TriangularTreasure;
import codewars_0602.sol.SortTheGiftCode;
import codewars_0603.sol.FunctionalAddition;
import codewars_0604.sol.LargestPairSumInArray;
import codewars_0605.sol.CamelCaseMethod;
import codewars_0606.sol.SortedYesNoHow;
import codewars_0607.sol.StripComments;
import codewars_0608.sol.MeanSquareError;
import codewars_0609.sol.MaximumProduct;
import codewars_0610.sol.Switcheroo;
import codewars_0611.sol.Factorial;
import codewars_0612.sol.EncryptThis;
import codewars_0613.sol.LostWithoutAMap;
import codewars_0614.sol.AnagramDetection;
import codewars_0615.sol.FindTheStrayNumber;
import codewars_0616.sol.MaximumLengthDifference;
import codewars_0617.sol.BuildTower;
import codewars_0618.sol.SortTheOdd;
import codewars_0619.sol.MakeTheDeadFishSwim;
import codewars_0620.sol.MakeAfunctionThatDoesArithmetic;
import codewars_0621.sol.PairOfGloves;
import codewars_0622.sol.SimpleMultiplication;
import codewars_0623.sol.CalculateStringRotation;
import codewars_0624.sol.RemoveExclamationMark;
import codewars_0625.sol.ContinuedFraction;
import codewars_0626.sol.LargestRadialSum;
import codewars_0627.sol.JennySecretMessage;
import codewars_0628.sol.BestTravel;
import codewars_0629.sol.VowelCount;
import codewars_0630.sol.ValidPhoneNumber;
import codewars_0701.sol.AreTheyTheSame;
import codewars_0702.sol.WeightForWeight;
import codewars_0703.sol.CenturyFromYear;
import codewars_0704.sol.PrinterErrors;
import codewars_0705.sol.CountingDuplicates;
import codewars_0706.sol.ProductOfConsecutiveFibNumbers;
import codewars_0707.sol.SoManyPermutations;
import codewars_0708.sol.Clock;
import codewars_0709.sol.IsThisATriangle;
import codewars_0710.sol.TribonacciSequence;

public class main {

	public static void main(String[] args) {
		Kata.evenOrOdd(0);	// 0221
		Solution sol = new Solution();	//0222
		System.out.println(sol.Solution(10));
		System.out.println(Vowels.getCount("abcoudefg "));	//0223
		System.out.println(Kata2.numberToString(123));
		System.out.println(Troll.disemvowel("This website is for losers LOL!"));
		System.out.println(Kata3.createPhoneNumber(new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 0}));
		System.out.println(Kata4.opposite(-10));
		System.out.println(Solution2.whoLikesIt("Peter, Sim"));
		System.out.println(SquareDigit.squareDigits(9119));
		System.out.println(YesOrNO.boolToWord(false));
		System.out.println(Solution3.repeatStr(20, "ABC"));
		System.out.println(HighAndLow.highAndLow("150 99 100 10 -10 25"));
		System.out.println(RemoveChars.remove("eloquent"));
		System.out.println(Arrays.toString(ArrayDiff.arrayDiff(new int[] {1, 2, 2, 2, 3}, new int[] {2})));
		System.out.println(DescendingOrder.sortDesc(1456456));
		System.out.println(SquareSum.squareSum(new int[]{1,2,2}));
		int u = 1;
//		System.out.println(ListFiltering.filterList(List.of(1,2,"a", "b")));
		System.out.println(HelloWorld.greet());
		System.out.println(SpinWords.spinWords("abcde abc bcdea"));
		System.out.println(IsoGram.isIsogram(""));
		System.out.println(ToJadenCase.toJadenCase(null));
		System.out.println(getXO.getXO("ppxxxxxooodd"));
		System.out.println(BitCounting.countBits(1234));
		System.out.println(DuplicateEncoder.encode("recede"));
		System.out.println(Accumul.accum("abcde"));
		System.out.println(FindOutlier.find(new int[]{-3, 0, 2, 4, 6}));
		System.out.println(TenMinWalk.isValid(new char[] {'w','e','w','e','w','e','w','e','w','e'}));
		System.out.println(StringToNumber.stringToNumber("150"));
		System.out.println(PigLatin.pigIt("Hello world !"));
		System.out.println(DnaStrand.makeComplement("ATTGC"));
		System.out.println(HumanReadableTime.makeReadable(359999));
		System.out.println(RemoveStringSpaces.noSpace("8 j 8   mBliB8g  imjB8B8  jl  B"));
		System.out.println(ConvertStringToCamelCase.toCamelCase("the-Stealth_Warrior"));
		System.out.println(HighestScoringWord.high("aa b"));
		System.out.println(DoubleInteger.doubleInteger(2));
		System.out.println(MaximumSubarray.sequence(new int[]{-2, 1, -3, 4, -1}));
		System.out.println(Maskify.maskify("Nananananananananananananananana Batman!"));	
		System.out.println(TwoToOne.longest("aretheyhere", "yestheyarehere"));
		System.out.println(Sum.GetSum(0, -1));
		System.out.println(GrowthOfAPopulation.nbYear(1500000, 0.25, 1000, 2000000));
		System.out.println(PangramChecker.check("The quick brown fox jumps over the lazy dog."));
		System.out.println(BinaryAddition.binaryAddition(1, 5));
		System.out.println(RgbToHex.rgb(255, 255, 300));
		System.out.println(FindTheNextPerfectSquare.findNextSquare(114));
		System.out.println(FindTheOddInt.findIt(new int[]{20,1,-1,2,-2,3,3,5,5,1,2,4,20,4,-1,-2,5}));
		System.out.println(StringSplit.solution("abcde"));
		System.out.println(CountingSheep.countSheeps(new Boolean[] {true,false,true,true,true}));
		System.out.println(YoureASquare.isSquare(26));
		System.out.println(NumberUnits.isNarcissistic(747729));
		System.out.println(DirReduction.dirReduc(new String[]{"EAST", "EAST", "WEST", "NORTH", "WEST", "EAST", "EAST", "SOUTH", "NORTH", "WEST"}));
		System.out.println(WhoLikesIt.whoLikesIt("Alex", "Jacob", "Mark", "Max"));
		System.out.println(SumOfDigits.digital_root(942));
		System.out.println(SmallestIntegerFinder.findSmallestInt(new int[] { 34,15,88,2}));
		System.out.println(PersistentBugger.persistence(39));
		System.out.println(YourOrderPlease.order("is2 Thi1s T4est 3a"));
		System.out.println(SumOfPositive.sum(new int[]{1,2,3,4,5}));
		System.out.println(FindTheUniqueNumber.findUniq(new double[] {0.5, 0.5, 0.1, 0.5} ));
		System.out.println(ShortestWord.findShort("bitcoin take over the world maybe who knows perhaps"));
		System.out.println(StringEndsWith.solution("samurai", "ai"));
		System.out.println(KeepHydrated.Liters(6.7));
		System.out.println(PeteTheBaker.cakes(Map.of(
				"flour", 500,
	            "sugar", 200,
	            "eggs", 1,
	            "cinnamon", 300), Map.of(
	            		"flour", 1200,
	                    "sugar", 1200,
	                    "eggs", 5,
	                    "milk", 200)));
		System.out.println(FirstNonRepeatingCharacter.firstNonRepeatingLetter("moon-men"));
		System.out.println(OnesAndZeros.ConvertBinaryArrayToInt(new ArrayList<>(Arrays.asList(0,0,0,1))));
		System.out.println(Scramblies.scramble("scriptjavx","javascript"));
		System.out.println(ReverseWords.reverseWords("This is an example!"));
		ArrayList<int[]> list = new ArrayList<int[]>();
	    list.add(new int[] {10,0});
	    list.add(new int[] {3,5});
	    list.add(new int[] {2,5});
		System.out.println(NumberOfPeopleInTheBus.countPassengers(list));
		System.out.println(BreakCamelCase.camelCase("camelCasingTest"));
		System.out.println(ReturningStrings.greet("Ryan"));
		System.out.println(OddOrEven.oddOrEven(new int[] {0, -1, -5}));
		System.out.println(IsNumberAPrime.isPrime(4));
		System.out.println(TheHighestProfitWins.minMax(new int[]{1,5}));
		System.out.println(Testing123.number(Arrays.asList("a", "b", "c")));
		System.out.println(WhichAreIn.inArray(new String[]{ "arp", "live", "strong" }, new String[] { "lively", "alive", "harp", "sharp", "armstrong" }));
		System.out.println(Factorial.factorial(5));
		System.out.println(MakeUpperCase.MakeUpperCase("hello"));
		System.out.println(OppositesAttract.isLove(0, 1));
		System.out.println(DontGiveMeFive.dontGiveMeFive(4, 17));
		System.out.println(BreakingChocolateProblem.breakChocolate(5, 5));
		System.out.println(BackspacesInString.cleanString("abc#d##c"));
		System.out.println(GreetMe.greet("npa6mni9v551hifkmikm1ilfbl"));
		System.out.println(SumOfNumbersFrom0ToN.showSequence(6));
		System.out.println(LeapYears.isLeapYear(2000));
		System.out.println(FixStringCase.solve("CODe"));
		System.out.println(CalculateAverage.find_average(new int[]{1, 2, 3, 4}));
		System.out.println(WriteNumberInExpandedForm.expandedForm(70304));
		System.out.println(RockPaperScissors.rps("rock", "scissors"));
		System.out.println(BumpsIntheRoad.bumps("_nnnnnnn_n__n______nn__nn_nnn"));
		System.out.println(BasicMathematicalOperations.basicMath("+", 5, 6));
		System.out.println(SumOfAngles.sumOfAngles(3));
		System.out.println(ReduceButGrow.grow(new int[]{4,1,1,1,4}));
		System.out.println(NotVerySecure.alphanumeric("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"));
		System.out.println(AlternateCapitalization.capitalize("codewars"));
		System.out.println(RomanNumeralsEncoder.solution(1666));
		System.out.println(SchoolPaperwork.paperWork(5, 5));
		System.out.println(SumArrays.sum(new double[] {1.1, 2.2, 3.3}));
		System.out.println(ReverseLetter.reverseLetter("ultr53o?n"));
		System.out.println(HowGoodAreYouReally.betterThanAverage(new int[] {12, 23, 34, 45, 56, 67, 78, 89, 90}, 69));
		System.out.println(TwoSum.twoSum(new int[]{1,2,3}, 4));
		System.out.println(HumanReadableDurationFormat.formatDuration(99253662));
		System.out.println(TriangularTreasure.triangular(1275));
		System.out.println(SortTheGiftCode.sortGiftCode("zyxwvutsrqponmlkjihgfedcba"));
		System.out.println(FunctionalAddition.add(3).applyAsInt(5));
		System.out.println(LargestPairSumInArray.largestPairSum(new int[]{-10,-8,-16,-18,-19}));
		System.out.println(CamelCaseMethod.camelCase(" camel case word"));
		System.out.println(SortedYesNoHow.isSortedAndHow(new int[] {15, 7, 3, -8}));
		System.out.println(StripComments.stripComments("apples, pears # and bananas\ngrapes\nbananas !apples", new String[] { "#", "!" }));
		System.out.println(MeanSquareError.solution(new int[]{10, 20, 10, 2}, new int[] {10, 25, 5, -2}));
		System.out.println(MaximumProduct.adjacentElementsProduct(new int[] {-23, 4, -5, 99, -27, 329, -2, 7, -921}));
		System.out.println(Switcheroo.switcheroo("bbbacccabbb"));
		System.out.println(Factorial.factorial(7));
		System.out.println(EncryptThis.encryptThis("A wise old owl lived in an oak"));
		System.out.println(LostWithoutAMap.map(new int[] {1, 2, 3}));
		System.out.println(AnagramDetection.isAnagram("Buckethead", "DeathCubeK"));
		System.out.println(FindTheStrayNumber.stray(new int[]{1,1,1,1,4}));
		System.out.println(MaximumLengthDifference.mxdiflg(new String[] { "hoqq", "bbllkw", "oox", "ejjuyyy", "plmiis", "xxxzgpsssa", "xxwwkktt", "znnnnfqknaz", "qqquuhii", "dvvvwz"}, new String[] {"cccooommaaqqoxii", "gggqaffhhh", "tttoowwwmmww"}));
		System.out.println(BuildTower.towerBuilder(6));
		System.out.println(SortTheOdd.sortArray(new int[]{ 5, 3, 2, 8, 1, 4 }));
		System.out.println(MakeTheDeadFishSwim.parse("iiisdosodddddiso"));
		System.out.println(MakeAfunctionThatDoesArithmetic.arithmetic(8, 2, "divide"));
		System.out.println(PairOfGloves.numberOfPairs(new String[] {"red", "green", "blue", "blue", "red", "green", "red", "red", "red"}));
		System.out.println(SimpleMultiplication.simpleMultiplication(9));
		System.out.println(CalculateStringRotation.shiftedDiff("coffee","eecoff"));
		System.out.println(RemoveExclamationMark.removeExclamationMarks("Hello World!"));
		System.out.println(ContinuedFraction.continuedFraction(311, 144));
		System.out.println(LargestRadialSum.largest(new int[]{1, 2, 3, 4}, 2));
		System.out.println(JennySecretMessage.greet("Johnny"));
		System.out.println(BestTravel.chooseBestSum(179, 3, new ArrayList<>(Arrays.asList(50, 55, 56, 57, 58))));
		System.out.println(VowelCount.getCount("o a kak ushakov lil vo kashu kakao"));
		System.out.println(ValidPhoneNumber.validPhoneNumber("(123) 456-7890"));
		System.out.println(AreTheyTheSame.comp(new int[]{121, 144, 19, 161, 19, 144, 19, 11}, new int[]{121, 14641, 20736, 361, 25921, 361, 20736, 361}));
		System.out.println(WeightForWeight.orderWeight("56 65 74 100 99 68 86 180 90"));
		System.out.println(CenturyFromYear.century(1705));
		System.out.println(PrinterErrors.printerError("aaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbmmmmmmmmmmmmmmmmmmmxyz"));
		System.out.println(CountingDuplicates.duplicateCount("indivisibility"));
		System.out.println(ProductOfConsecutiveFibNumbers.productFib(4895));
		System.out.println(SoManyPermutations.singlePermutations("abcde"));
		System.out.println(Clock.Past(0, 1, 1));
		System.out.println(IsThisATriangle.isTriangle(7,2,2));
		System.out.println(TribonacciSequence.tribonacci(new double []{1,1,1},10));
	}

}
